p8105_hw2_ejc2222
================
Emanuel Clemente
2026-10-08

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

### Reading & Cleaning the Data

``` r
transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |> 
  janitor::clean_names() |> 
  select(line, station_name, station_latitude, station_longitude,
         route1:route11, entry, vending, entrance_type, ada) |> 
  mutate(entry = if_else(entry == "YES", TRUE, FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset contains information on each entrance and exit for each
subway station in New York City. The variables retained are line,
station name, station latitude/longitude, routes served (`route1`
through `route11`), entry, vending, entrance type, and ADA compliance. I
read in the data with `read_csv()`, cleaned the variable names with
`janitor::clean_names()`, kept the specified variables with `select()`,
and used `mutate()` to convert `entry` from “YES”/“NO” to a logical
variable (`TRUE`/`FALSE`). The resulting dataset has 1868 rows and 19
columns. The NAs in the route columns reflect stations that serve fewer
than 11 routes, not missing data.

### Questions

``` r
n_stations = 
  transit_df |> 
  distinct(line, station_name) |> 
  nrow()

n_ada = 
  transit_df |> 
  filter(ada) |> 
  distinct(line, station_name) |> 
  nrow()

prop_no_vending = 
  transit_df |> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```

There are 465 distinct stations, 84 of which are ADA compliant.
Approximately 37.7% of station entrances/exits without vending allow
entrance.

### Reformatting Route Number and Route Name

To make route number and route name distinct variables, I converted
`route8` through `route11` to character so all route columns share the
same type, then used `pivot_longer()` to collapse the 11 route columns
into `route_number` and `route_name`, dropping empty route slots.

``` r
transit_long_df = 
  transit_df |> 
  mutate(across(route8:route11, as.character)) |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    names_prefix = "route",
    values_drop_na = TRUE
  )
```

``` r
n_a_stations = 
  transit_long_df |> 
  filter(route_name == "A") |> 
  distinct(line, station_name) |> 
  nrow()

n_a_ada = 
  transit_long_df |> 
  filter(route_name == "A", ada) |> 
  distinct(line, station_name) |> 
  nrow()
```

60 distinct stations serve the A train, and 17 of those are ADA
compliant.

## Problem 2

### Reading & Cleaning the Data

``` r
mr_trash_df = 
  read_excel(
    "./data/202610_trash_wheel_collection_data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  ) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "Mr. Trash Wheel"
  )

prof_trash_df = 
  read_excel(
    "./data/202610_trash_wheel_collection_data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    na = c("", "NA", "dive")
  ) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(trash_wheel = "Professor Trash Wheel")

gwynnda_df = 
  read_excel(
    "./data/202610_trash_wheel_collection_data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394"
  ) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(trash_wheel = "Gwynnda")
```

``` r
trash_wheel_df = 
  bind_rows(mr_trash_df, prof_trash_df, gwynnda_df) |> 
  relocate(trash_wheel)
```

``` r
prof_total_weight = 
  trash_wheel_df |> 
  filter(trash_wheel == "Professor Trash Wheel") |> 
  pull(weight_tons) |> 
  sum(na.rm = TRUE)

gwynnda_butts_june_2022 = 
  trash_wheel_df |> 
  filter(trash_wheel == "Gwynnda", year == 2022, month == "June") |> 
  pull(cigarette_butts) |> 
  sum(na.rm = TRUE)
```

The combined dataset contains 1269 observations, each representing a
single dumpster of trash collected by Mr. Trash Wheel, Professor Trash
Wheel, or Gwynnda. Key variables include `trash_wheel`, which identifies
the source, along with `date`, `weight_tons`, `volume_cubic_yards`,
specific items such as `plastic_bottles` and `cigarette_butts`, and
`homes_powered`. We should note that `sports_balls` is only recorded for
Mr. Trash Wheel, and `glass_bottles` is not recorded for Gwynnda, so
these are NA for the other wheels. Professor Trash Wheel collected a
total of 294.96 tons of trash, and Gwynnda collected 18,120 cigarette
butts in June 2022.

## Problem 3

### Baseline Demographics

``` r
baseline_df = 
  read_csv("./data/MCI_baseline.csv", skip = 1, na = c("NA", "", ".")) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(sex, 1 ~ "male", 0 ~ "female"),
    apoe4 = case_match(apoe4, 1 ~ "carrier", 0 ~ "non-carrier")
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `sex = case_match(sex, 1 ~ "male", 0 ~ "female")`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
demographics_df = 
  baseline_df |> 
  filter(is.na(age_at_onset) | age_at_onset > current_age)
```

``` r
n_recruited = nrow(baseline_df)
n_eligible = nrow(demographics_df)

n_mci = 
  demographics_df |> 
  filter(!is.na(age_at_onset)) |> 
  nrow()

mean_age = mean(demographics_df$current_age)

prop_women_apoe4 = 
  demographics_df |> 
  filter(sex == "female") |> 
  summarize(prop = mean(apoe4 == "carrier")) |> 
  pull(prop)
```

### Longitudinal Amyloid Data

``` r
amyloid_df = 
  read_csv("./data/mci_amyloid.csv", skip = 1, na = c("NA", "Na")) |> 
  janitor::clean_names() |> 
  rename(id = study_id, time_0 = baseline) |> 
  pivot_longer(
    time_0:time_8,
    names_to = "years_since_baseline",
    names_prefix = "time_",
    names_transform = as.numeric,
    values_to = "amyloid_ratio"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Checking Overlap and Combining

``` r
only_baseline = anti_join(demographics_df, amyloid_df, by = "id")

only_amyloid = 
  anti_join(amyloid_df, demographics_df, by = "id") |> 
  distinct(id)

mci_df = inner_join(demographics_df, amyloid_df, by = "id")

write_csv(mci_df, "./data/mci_combined.csv")
```

483 participants were recruited and 4 had MCI at or before baseline and
were excluded, which leaves 479. During follow-up: 93 of the 479
developed MCI. The average age at baseline was 65.0 years. Among women,
30% of women (63 of 210) are carriers of APOE4. In the combined dataset,
there are 471 participants, and its dimensions are 2,355 rows, and 8
columns.
